Repository terraform-lxd/terraform-provider-lxd, pull requests merged in 2023-11, with the labels that each got.

#370 fix tests using alpine images
  docs/resources/project.md
  lxd/import_resource_lxd_container_test.go
  lxd/resource_lxd_cached_image_test.go
  lxd/resource_lxd_container_file_test.go
  lxd/resource_lxd_container_test.go
  lxd/resource_lxd_instance_file_test.go
  lxd/resource_lxd_instance_test.go
  lxd/resource_lxd_network_lb_test.go
  lxd/resource_lxd_network_test.go
  lxd/resource_lxd_profile_test.go
  lxd/resource_lxd_publish_image_test.go
  lxd/resource_lxd_snapshot_test.go
  lxd/resource_lxd_volume_container_attach_test.go
  lxd/resource_lxd_volume_test.go
Labels: chore

#378 Drop deprecated provider parameters
  lxd/provider.go
Labels: breaking-change

#377 Drop deprecated lxd_container and lxd_container_file resources
  .github/workflows/test.yml
  docs/resources/container.md
  docs/resources/container_file.md
  lxd/import_resource_lxd_container_test.go
  lxd/provider.go
  lxd/resource_lxd_container.go
  lxd/resource_lxd_container_file.go
  lxd/resource_lxd_container_file_test.go
  lxd/resource_lxd_container_test.go
  lxd/resource_lxd_network_test.go
  lxd/resource_lxd_profile_test.go
  lxd/resource_lxd_publish_image_test.go
  lxd/resource_lxd_snapshot_test.go
  lxd/resource_lxd_volume_test.go
Labels: breaking-change

#384 tests: don't run pr when converting from draft
  .github/workflows/test.yml
Labels: testing

#383 Support `config.cloud-init.*` keys
  lxd/resource_lxd_instance.go
  lxd/resource_lxd_instance_test.go
Labels: enhancement
