Repository terraform-lxd/terraform-provider-lxd, pull requests merged in 2023-10, with the labels that each got.

#360 Add load balancer resource
  .github/workflows/test.yml
  docs/resources/network_load_balancer.md
  lxd/provider.go
  lxd/resource_lxd_network_lb.go
  lxd/resource_lxd_network_lb_test.go
  lxd/utils.go
Labels: enhancement

#364 testing: cleanup and catch more
  .github/workflows/test.yml
Labels: testing

#365 Fix unix socket check on Windows
  lxd/fs_unix.go
  lxd/fs_windows.go
  lxd/provider.go
Labels: bug
