Repository terraform-lxd/terraform-provider-lxd, pull requests merged in 2024-08, with the labels that each got.

#505 Allow null description in LB backend and port
  internal/network/resource_network_lb.go
  internal/network/resource_network_lb_test.go
Labels: bug

#504 Add network peer resource
  docs/resources/network_peer.md
  internal/network/resource_network_peer.go
  internal/network/resource_network_peer_test.go
  internal/provider/provider.go
Labels: enhancement

#510 Allow managing default profiles in non-default projects
  docs/resources/profile.md
  internal/profile/resource_profile.go
  internal/profile/resource_profile_test.go
Labels: enhancement

#509 Don't check fingerprint if 'Content' is unknown
  internal/truststore/trust_certificate.go
Labels: bug

#516 Remove LXD version check during password auth
  internal/provider-config/config.go
Labels: bug

#512 Add trust token resource
  docs/resources/trust_token.md
  internal/provider/provider.go
  internal/truststore/trust_token.go
  internal/truststore/trust_token_test.go
Labels: enhancement

#518 Refactor provider config and test trust token/password
  .github/workflows/test.yml
  docs/index.md
  go.mod
  internal/acctest/checks.go
  internal/acctest/provider_factory.go
  internal/provider-config/config.go
  internal/provider-config/config_test.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_noop.go
Labels: breaking-change
