Repository terraform-lxd/terraform-provider-lxd, pull requests merged in 2025-02, with the labels that each got.

#557 Misc cleanup
  .github/workflows/test.yml
  README.md
  go.mod
  go.sum
  internal/provider-config/config.go
Labels: chore

#559 Allow cluster member group as target and handle in-cluster migration
  docs/resources/instance.md
  internal/instance/resource_instance.go
  internal/instance/resource_instance_test.go
Labels: bug

#560 Profile, project, and image datasources (from Incus)
  docs/data-sources/image.md
  docs/data-sources/profile.md
  docs/data-sources/project.md
  internal/image/datasource_image.go
  internal/image/datasource_image_test.go
  internal/image/schema_validators.go
  internal/profile/datasource_profile.go
  internal/profile/datasource_profile_test.go
  internal/project/datasource_project.go
  internal/project/datasource_project_test.go
  internal/provider/provider.go
Labels: enhancement

#562 Add network, storage pool and instance datasources
  docs/data-sources/image.md
  docs/data-sources/instance.md
  docs/data-sources/network.md
  docs/data-sources/storage_pool.md
  internal/common/lxd_device.go
  internal/image/datasource_image.go
  internal/instance/datasource_instance.go
  internal/instance/datasource_instance_test.go
  internal/instance/resource_instance.go
  internal/network/datasource_network.go
  internal/network/datasource_network_test.go
  internal/profile/datasource_profile.go
  internal/project/datasource_project.go
  internal/provider/provider.go
  internal/storage/datasource_storage_pool.go
  internal/storage/datasource_storage_pool_test.go
Labels: enhancement

#568 instance_file: Fix file removal and panic when file is not found
  internal/instance/resource_instance_file.go
Labels: bug
